name: Upload files to S3 and CloudFront

on:
  push:
    branches:
    - main

env:
  SOURCE_DIR: './out'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn run build
      env:
            AWS_CLOUDFRONT_URL: ${{ secrets.AWS_CLOUDFRONT_URL }}

    - name: "Configure AWS Credentials"
      # You may pin to the exact commit or the version.
      # uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Sync files to S3
      run: |
          aws s3 sync ${{ env.SOURCE_DIR }} ${{ secrets.AWS_S3_BUCKET }} --delete --exclude '.*git*'
    - name: Invalidate CloudFront Cache
      run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
